#!/usr/bin/env bash

read -p 'Repository: ' repository
read -p 'Reason: ' reason
read -p 'Removal type: ' removal_type
read -p 'Link to more information: ' link

echo $repository
echo $reason
echo $removal_type
echo $link

python3 $(dirname "$0")/remove_repo.py "$repository" "$removal_type" "$reason" "$link" || exit 0
