name: "Check"
on:
  pull_request:

jobs:
  preflight:
    runs-on: ubuntu-latest
    name: Preflight
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone hacs/default:origin
        run: git clone --depth 1 https://github.com/hacs/default /tmp/repositories/default

      - name: Clone the new repository
        run: |
          repo=$(python3 -m scripts.changed.repo)
          git clone --depth 1 "https://github.com/$repo" /tmp/repositories/addition || exit 1

      - name: Cleanup
        run: |
          rm -rf /tmp/repos/hacs/addition/.git
          rm -rf /tmp/repos/hacs/default/.git
          rm -rf /tmp/repos/hacs/default/scripts

      - name: Upload shared artifact
        uses: actions/upload-artifact@master
        with:
          name: repositories
          path: /tmp/repositories

  download:
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download shared artifact
        uses: actions/download-artifact@master
        with:
          name: repositories
          path: /tmp/repositories