name: "Check Manifest"
on:
    pull_request:
        branches:
            - master

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Clone origin
              run: git clone https://github.com/hacs/default /tmp/default

            - name: Clone new addition
              run: |
                repo=$(python3 -m scripts.changed.repo)
                git clone "https://github.com/$repo" /tmp/addition

            - name: Check manifest
              run: python3 -m scripts.check.manifest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}