name: "Check test"
on:
  pull_request:




jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Clone origin
              run: git clone --depth 1 https://github.com/hacs/default /tmp/default


            - uses: actions/upload-artifact@master
              with:
                name: default
                path: /tmp/default

    download:
        runs-on: ubuntu-latest
        needs: upload
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - uses: actions/download-artifact@master
              with:
                name: default
                path: /tmp/default