name: Validate with HACS

on:
  push:
  pull_request:

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration