name: Hassfest
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
