name: Validate
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@main
        with:
          category: integration
